-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	icons = {
		Back = {
			Image = "rbxassetid://10223805866",
			ImageRectOffset = Vector2.new(0, 0),
			ImageRectSize = Vector2.new(24, 24),
		},
		Check = {
			Image = "rbxassetid://10223805866",
			ImageRectOffset = Vector2.new(25, 0),
			ImageRectSize = Vector2.new(24, 24),
		},
		Chevron = {
			Image = "rbxassetid://10223805866",
			ImageRectOffset = Vector2.new(75, 0),
			ImageRectSize = Vector2.new(20, 20),
		},
		CurlyBraces = {
			Image = "rbxassetid://10223805866",
			ImageRectOffset = Vector2.new(0, 25),
			ImageRectSize = Vector2.new(24, 24),
		},
		Delete = {
			Image = "rbxassetid://10223805866",
			ImageRectOffset = Vector2.new(50, 25),
			ImageRectSize = Vector2.new(20, 20),
		},
		Export = {
			Image = "rbxassetid://10223805866",
			ImageRectOffset = Vector2.new(25, 50),
			ImageRectSize = Vector2.new(20, 20),
		},
		Folder = {
			Image = "rbxassetid://10223805866",
			ImageRectOffset = Vector2.new(50, 0),
			ImageRectSize = Vector2.new(24, 24),
		},
		Import = {
			Image = "rbxassetid://10223805866",
			ImageRectOffset = Vector2.new(0, 75),
			ImageRectSize = Vector2.new(20, 20),
		},
		Menu = {
			Image = "rbxassetid://10223805866",
			ImageRectOffset = Vector2.new(25, 25),
			ImageRectSize = Vector2.new(24, 24),
		},
		Refresh = {
			Image = "rbxassetid://10223805866",
			ImageRectOffset = Vector2.new(0, 50),
			ImageRectSize = Vector2.new(24, 24),
		},
		Rewind = {
			Image = "rbxassetid://10223805866",
			ImageRectOffset = Vector2.new(96, 0),
			ImageRectSize = Vector2.new(20, 20),
		},
		Search = {
			Image = "rbxassetid://10223805866",
			ImageRectOffset = Vector2.new(75, 21),
			ImageRectSize = Vector2.new(20, 20),
		},
	},
}